---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: docker.io/library/influxdb:1.12
          ports:
            - containerPort: 8087
              hostPort: 8087
          volumeMounts:
            - name: influxdb-storage
              mountPath: /var/lib/influxdb
          env:
            - name: INFLUXDB_DB
              value: testing
            - name: INFLUXDB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: admin-user
            - name: INFLUXDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: admin-password
            - name: INFLUXDB_HTTP_BIND_ADDRESS
              value: ":8087"
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: false
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
        - name: chronograf
          image: docker.io/library/chronograf:latest
          ports:
            - containerPort: 8888
              hostPort: 8888
          volumeMounts:
            - name: chronograf-storage
              mountPath: /var/lib/chronograf
          env:
            - name: INFLUXDB_URL
              value: http://influxdb:8087
            - name: INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: admin-user
            - name: INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: admin-password
      volumes:
        - name: chronograf-storage
          persistentVolumeClaim:
            claimName: chronograf-storage
---
kind: Secret
apiVersion: v1
metadata:
  name: influxdb-credentials
data:
  admin-user: dGVzdGVy  # <- tester
  admin-password: cGFzc3cwcmQ=  # <- passw0rd
